/** @format */
import React, { Component } from "react";

//import ComponentLayout from "../layout/layout";
import ComponentLayout from "../layout/layout";

export default class Post extends Component {

  render() {
    return ComponentLayout(
        <div>
          <h1>Hola </h1>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae maiores dignissimos atque eius nam vero, tenetur perferendis, cupiditate error incidunt dolore ab nulla. Quidem deserunt ipsum temporibus cum dolor laboriosam asperiores molestiae necessitatibus distinctio, labore corrupti, obcaecati dolorem non quas facere. Incidunt cupiditate cum sequi nostrum sit accusantium, saepe qui repellat mollitia perspiciatis culpa reiciendis impedit, atque delectus ab quis rem. Adipisci impedit debitis, nemo qui quam saepe nulla mollitia culpa odit iusto quasi aliquam praesentium provident placeat aspernatur illum ab assumenda exercitationem. Explicabo aut, obcaecati ullam. Nostrum, numquam aperiam iure iste neque earum sapiente dicta cupiditate, quas fugiat rem.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae maiores dignissimos atque eius nam vero, tenetur perferendis, cupiditate error incidunt dolore ab nulla. Quidem deserunt ipsum temporibus cum dolor laboriosam asperiores molestiae necessitatibus distinctio, labore corrupti, obcaecati dolorem non quas facere. Incidunt cupiditate cum sequi nostrum sit accusantium, saepe qui repellat mollitia perspiciatis culpa reiciendis impedit, atque delectus ab quis rem. Adipisci impedit debitis, nemo qui quam saepe nulla mollitia culpa odit iusto quasi aliquam praesentium provident placeat aspernatur illum ab assumenda exercitationem. Explicabo aut, obcaecati ullam. Nostrum, numquam aperiam iure iste neque earum sapiente dicta cupiditate, quas fugiat rem.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae maiores dignissimos atque eius nam vero, tenetur perferendis, cupiditate error incidunt dolore ab nulla. Quidem deserunt ipsum temporibus cum dolor laboriosam asperiores molestiae necessitatibus distinctio, labore corrupti, obcaecati dolorem non quas facere. Incidunt cupiditate cum sequi nostrum sit accusantium, saepe qui repellat mollitia perspiciatis culpa reiciendis impedit, atque delectus ab quis rem. Adipisci impedit debitis, nemo qui quam saepe nulla mollitia culpa odit iusto quasi aliquam praesentium provident placeat aspernatur illum ab assumenda exercitationem. Explicabo aut, obcaecati ullam. Nostrum, numquam aperiam iure iste neque earum sapiente dicta cupiditate, quas fugiat rem.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae maiores dignissimos atque eius nam vero, tenetur perferendis, cupiditate error incidunt dolore ab nulla. Quidem deserunt ipsum temporibus cum dolor laboriosam asperiores molestiae necessitatibus distinctio, labore corrupti, obcaecati dolorem non quas facere. Incidunt cupiditate cum sequi nostrum sit accusantium, saepe qui repellat mollitia perspiciatis culpa reiciendis impedit, atque delectus ab quis rem. Adipisci impedit debitis, nemo qui quam saepe nulla mollitia culpa odit iusto quasi aliquam praesentium provident placeat aspernatur illum ab assumenda exercitationem. Explicabo aut, obcaecati ullam. Nostrum, numquam aperiam iure iste neque earum sapiente dicta cupiditate, quas fugiat rem.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae maiores dignissimos atque eius nam vero, tenetur perferendis, cupiditate error incidunt dolore ab nulla. Quidem deserunt ipsum temporibus cum dolor laboriosam asperiores molestiae necessitatibus distinctio, labore corrupti, obcaecati dolorem non quas facere. Incidunt cupiditate cum sequi nostrum sit accusantium, saepe qui repellat mollitia perspiciatis culpa reiciendis impedit, atque delectus ab quis rem. Adipisci impedit debitis, nemo qui quam saepe nulla mollitia culpa odit iusto quasi aliquam praesentium provident placeat aspernatur illum ab assumenda exercitationem. Explicabo aut, obcaecati ullam. Nostrum, numquam aperiam iure iste neque earum sapiente dicta cupiditate, quas fugiat rem.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae maiores dignissimos atque eius nam vero, tenetur perferendis, cupiditate error incidunt dolore ab nulla. Quidem deserunt ipsum temporibus cum dolor laboriosam asperiores molestiae necessitatibus distinctio, labore corrupti, obcaecati dolorem non quas facere. Incidunt cupiditate cum sequi nostrum sit accusantium, saepe qui repellat mollitia perspiciatis culpa reiciendis impedit, atque delectus ab quis rem. Adipisci impedit debitis, nemo qui quam saepe nulla mollitia culpa odit iusto quasi aliquam praesentium provident placeat aspernatur illum ab assumenda exercitationem. Explicabo aut, obcaecati ullam. Nostrum, numquam aperiam iure iste neque earum sapiente dicta cupiditate, quas fugiat rem.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae maiores dignissimos atque eius nam vero, tenetur perferendis, cupiditate error incidunt dolore ab nulla. Quidem deserunt ipsum temporibus cum dolor laboriosam asperiores molestiae necessitatibus distinctio, labore corrupti, obcaecati dolorem non quas facere. Incidunt cupiditate cum sequi nostrum sit accusantium, saepe qui repellat mollitia perspiciatis culpa reiciendis impedit, atque delectus ab quis rem. Adipisci impedit debitis, nemo qui quam saepe nulla mollitia culpa odit iusto quasi aliquam praesentium provident placeat aspernatur illum ab assumenda exercitationem. Explicabo aut, obcaecati ullam. Nostrum, numquam aperiam iure iste neque earum sapiente dicta cupiditate, quas fugiat rem.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae maiores dignissimos atque eius nam vero, tenetur perferendis, cupiditate error incidunt dolore ab nulla. Quidem deserunt ipsum temporibus cum dolor laboriosam asperiores molestiae necessitatibus distinctio, labore corrupti, obcaecati dolorem non quas facere. Incidunt cupiditate cum sequi nostrum sit accusantium, saepe qui repellat mollitia perspiciatis culpa reiciendis impedit, atque delectus ab quis rem. Adipisci impedit debitis, nemo qui quam saepe nulla mollitia culpa odit iusto quasi aliquam praesentium provident placeat aspernatur illum ab assumenda exercitationem. Explicabo aut, obcaecati ullam. Nostrum, numquam aperiam iure iste neque earum sapiente dicta cupiditate, quas fugiat rem.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae maiores dignissimos atque eius nam vero, tenetur perferendis, cupiditate error incidunt dolore ab nulla. Quidem deserunt ipsum temporibus cum dolor laboriosam asperiores molestiae necessitatibus distinctio, labore corrupti, obcaecati dolorem non quas facere. Incidunt cupiditate cum sequi nostrum sit accusantium, saepe qui repellat mollitia perspiciatis culpa reiciendis impedit, atque delectus ab quis rem. Adipisci impedit debitis, nemo qui quam saepe nulla mollitia culpa odit iusto quasi aliquam praesentium provident placeat aspernatur illum ab assumenda exercitationem. Explicabo aut, obcaecati ullam. Nostrum, numquam aperiam iure iste neque earum sapiente dicta cupiditate, quas fugiat rem.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae maiores dignissimos atque eius nam vero, tenetur perferendis, cupiditate error incidunt dolore ab nulla. Quidem deserunt ipsum temporibus cum dolor laboriosam asperiores molestiae necessitatibus distinctio, labore corrupti, obcaecati dolorem non quas facere. Incidunt cupiditate cum sequi nostrum sit accusantium, saepe qui repellat mollitia perspiciatis culpa reiciendis impedit, atque delectus ab quis rem. Adipisci impedit debitis, nemo qui quam saepe nulla mollitia culpa odit iusto quasi aliquam praesentium provident placeat aspernatur illum ab assumenda exercitationem. Explicabo aut, obcaecati ullam. Nostrum, numquam aperiam iure iste neque earum sapiente dicta cupiditate, quas fugiat rem.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae maiores dignissimos atque eius nam vero, tenetur perferendis, cupiditate error incidunt dolore ab nulla. Quidem deserunt ipsum temporibus cum dolor laboriosam asperiores molestiae necessitatibus distinctio, labore corrupti, obcaecati dolorem non quas facere. Incidunt cupiditate cum sequi nostrum sit accusantium, saepe qui repellat mollitia perspiciatis culpa reiciendis impedit, atque delectus ab quis rem. Adipisci impedit debitis, nemo qui quam saepe nulla mollitia culpa odit iusto quasi aliquam praesentium provident placeat aspernatur illum ab assumenda exercitationem. Explicabo aut, obcaecati ullam. Nostrum, numquam aperiam iure iste neque earum sapiente dicta cupiditate, quas fugiat rem.</p>
        </div>
    );
  }
}
